name: deployments
on:
  push:
    branches:
      - main
      - dev

jobs:
  staging:
    name: STAGE DEPLOYMENT
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment:
      name: STAGING
    steps:
      - name: Referring environment variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER }}"
      - name: Referring environment secrets
        run: echo "[INFO] Password for ${{ vars.USER }} is ${{ secrets.PASSWORD }}"

  production:
    name: PROD DEPLOYMENT
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: PRODUCTION
    steps:
      - name: Referring environment variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER }}"
      - name: Referring environment secrets
        run: echo "[INFO] Password for ${{ vars.USER }} is ${{ secrets.PASSWORD }}"
