name: my-first-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ENV_TYPE: DEV
  APP_USER: thinknyx
  APP_PORT: 80
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 - Checkout
        uses: actions/checkout@v6.0.2
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt 
          ls -ltr
          hostname
      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
          name: single_file
          path: ./myartifact.txt
  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking current directory
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: single_file
      - name: Download single file artifact post download
        run: |
          pwd
          ls -ltr
      - name: Referring Environment Variables
        run: |
          echo "[INFO] Running Deployment for $ENV_TYPE with user $APP_USER"
          echo "[INFO] Once Deployed  application is accessible on port $APP_PORT"
      - name: Referring repository secret
        run: |
          echo "[INFO] Application password is ${{ secrets.APP_PASSWORD }}"
      - name: Step for PR Demos
        run: exit 0
  job3:
    name: JOB3
    runs-on: ubuntu-latest
    steps:
      - name: Referring context on in-built variables
        run: |
          echo "[INFO] Triggered by ${{ github.event_name }}"
          echo "[INFO] New changed are added by ${{ github.actor }} in ${{ github.head_ref }}"
          echo "[INFO] Current Step is running on ${{ runner.os }}"
          echo "[INFO] Current JOB ID is ${{ job.check_run_id }}"
  staging:
    name: STAGE DEPLOYMENT
    runs-on: ubuntu-latest
    steps:
      - name: Referring environment variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER}}"
      - name: Referring environment secrets
        run: echo "[INFO] Password for ${{ vars.USER}} is ${{ secrets.PASSWORD }}"
    environment:
      name: STAGING
    if: github.head_ref == 'dev'
  pruduction:
    name: PROD DEPLOYMENT
    runs-on: ubuntu-latest
    steps:
      - name: Referring environment variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER}}"
      - name: Referring environment secrets
        run: echo "[INFO] Password for ${{ vars.USER}} is ${{ secrets.PASSWORD }}"
    environment:
      name: PRODUCTION
    if: github.ref == 'refs/heads/main'